CMAKE_MINIMUM_REQUIRED(VERSION 3.14)

find_package(Qt5 REQUIRED COMPONENTS Core Gui)
find_package(DtkCore REQUIRED)
find_package(DtkGui REQUIRED)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(AUTOMOC_COMPILER_PREDEFINES ON)

list(APPEND GLOBAL_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/dpluginloader.h
)
list(APPEND GLOBAL_SOURCES
    main.cpp
)

add_definitions(-DTARGET=\"lib${PLUGIN_NAME}\")
add_definitions(-DBASED_DTK_DIR=\"${BASED_DTK_DIR}\")

SET(LIBRARY_OUTPUT_PATH ${CMAKE_SOURCE_DIR}/bin/plugins/${PLUGIN_TYPE})
add_library(${PROJECT_NAME} MODULE main.cpp ${GLOBAL_SOURCES} ${GLOBAL_HEADERS})
SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES OUTPUT_NAME ${PLUGIN_NAME})

list(APPEND COMMON_LIBS
    Qt5::Core
    Qt5::Gui
    ${DtkGui_LIBRARIES}
)

target_link_libraries(${PROJECT_NAME} PUBLIC ${COMMON_LIBS})

target_include_directories(${PROJECT_NAME} PUBLIC
    ${CMAKE_CURRENT_BINARY_DIR}
    ${CMAKE_SOURCE_DIR}
    ${DtkGui_INCLUDE_DIRS}
    ${Qt5Gui_PRIVATE_INCLUDE_DIRS}
    ${CMAKE_CURRENT_LIST_DIR}
)

install(TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_LIBDIR}/qt5/plugins/${PLUGIN_TYPE})
