/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./qt5integration/platformthemeplugin/xmls/com.deepin.filemanager.filedialogmanager.xml -a ./qt5integration/toolGenerate/qdbusxml2cpp/com.deepin.filemanager.filedialogmanagerAdaptor -i ./qt5integration/toolGenerate/qdbusxml2cpp/com.deepin.filemanager.filedialogmanager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_FILEMANAGER_FILEDIALOGMANAGERADAPTOR_H
#define COM_DEEPIN_FILEMANAGER_FILEDIALOGMANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./qt5integration/toolGenerate/qdbusxml2cpp/com.deepin.filemanager.filedialogmanager.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.filemanager.filedialogmanager
 */
class FiledialogmanagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.filemanager.filedialogmanager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.filemanager.filedialogmanager\">\n"
"    <method name=\"createDialog\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"destroyDialog\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"dialogs\">\n"
"      <arg direction=\"out\" type=\"ao\" name=\"dialogObjectList\"/>\n"
"    </method>\n"
"    <method name=\"errorString\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"error\"/>\n"
"    </method>\n"
"    <method name=\"isUseFileChooserDialog\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"ok\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    FiledialogmanagerAdaptor(QObject *parent);
    virtual ~FiledialogmanagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath createDialog(const QString &key);
    void destroyDialog(const QDBusObjectPath &path);
    QList<QDBusObjectPath> dialogs();
    QString errorString();
    bool isUseFileChooserDialog();
Q_SIGNALS: // SIGNALS
};

#endif
