/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./qt5integration/imageformatplugins/dci/image-dci.xml -a ./qt5integration/toolGenerate/qdbusxml2cpp/image-dciAdaptor -i ./qt5integration/toolGenerate/qdbusxml2cpp/image-dci.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./qt5integration/toolGenerate/qdbusxml2cpp/image-dciAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

